baseurl = "https://qantasairways.github.io/"
languageCode = "en-au"
title = "Qantas Code"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "Qantas Code Blog"
  defaultTheme = "light"

[params.logo]
  path = "/img/qantas-code-logo.svg"
  alt = "qantas code logo"

[menu]
  [[menu.main]]
    identifier = "playbook"
    name = "Playbook"
    url = "/playbook"
  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers"